
version: 2

sources:
  - name: dbsales
    schema: public
    tables:
      - name: commodities
        description: "Tabela que contem dados historicos de commodities"
        columns:
          - name: Date
            description: "Data da cotacao"
          - name: Close
            description: "Preco de fechamento da commodity"
          - name: simbolo
            description: "Simbolo da commodity"